### ISSUE TITLE
How much improved performance on GTX 1080 Ti Extreme?

### ISSUE THREAD

**Issue by davidye2020** [koban6/Ray#50]
If running on GTX 1080 Ti Extreme vs 750Ti Mini, is there a marked improvement in skill?

**Comment by zakki** [comment]
koban6's Ray doesn't use GPU. I think it's about my fork Rn.
1080 Ti is 8x FLOPS than 750 Ti, so it improves Rn's policy and value network speed.
If CPU is good enough, 1080 Ti improves strength.

**Comment by koban6** [comment]
Closed
